server:
  port: 8082
  servlet:
    session:
      timeout: 5m

springdoc:
  swagger-ui:
    path: swagger
    operationsSorter: method

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/WebBooking
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION