export enum MarginTypes {
    top = 'top',
    x1 = 'x1',
    x2 = 'x2',
    top_x2 = 'top_x2',
    top_x3 = 'top_x3',
    left = 'left',
    left_x2 = 'left_x2',
    left_x3 = 'left_x3',
    right = 'right',
    right_x2 = 'right_x2',
    right_x3 = 'right_x3',
    bottom = 'bottom',
    bottom_x2 = 'bottom_x2',
    bottom_x3 = 'bottom_x3',
    default = '',
}

export enum PaddingTypes {
    top = 'top',
    x1 = 'x1',
    x2 = 'x2',
    top_x2 = 'top_x2',
    top_x3 = 'top_x3',
    left = 'left',
    left_x2 = 'left_x2',
    left_x3 = 'left_x3',
    right = 'right',
    right_x2 = 'right_x2',
    right_x3 = 'right_x3',
    bottom = 'bottom',
    bottom_x2 = 'bottom_x2',
    bottom_x3 = 'bottom_x3',
    default = '',
}